name: FlutterPractice
description: Flutterフレームワークの検証

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0
  english_words: ^3.1.0
  battery: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.1.2
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

