name: FlutterPractice
description: Flutterフレームワークの検証

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0
  english_words: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.1.2
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/sandwich.jpg
    - images/autumn-table1.jpg
    - images/autumn-tree1.jpg
    - images/thumbnail/sandwich-100.jpg
    - images/thumbnail/autumn-table1-100.jpg
    - images/thumbnail/autumn-tree1-100.jpg

